# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oak < Formula
  desc "CLI for Oak, a Git proxy with fine-grained access control"
  homepage "https://oakling.dev"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oakling-dev/homebrew-tap/releases/download/v0.0.2/oak_0.0.2_darwin_amd64.tar.gz"
      sha256 "ca7995a03413212f6f027db9d509a17e3d44d604fc31e91018fb28c1cc624763"

      def install
        bin.install "oak"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oakling-dev/homebrew-tap/releases/download/v0.0.2/oak_0.0.2_darwin_arm64.tar.gz"
      sha256 "c7a52b087313b01cef5ea1ffc4c3f93fb53100e03473b3d6efa086ba6fe8ee1f"

      def install
        bin.install "oak"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oakling-dev/homebrew-tap/releases/download/v0.0.2/oak_0.0.2_linux_amd64.tar.gz"
      sha256 "c5385447631c99d5338046899679547b6282f73840476282811a2f50acdbd101"
      def install
        bin.install "oak"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oakling-dev/homebrew-tap/releases/download/v0.0.2/oak_0.0.2_linux_arm64.tar.gz"
      sha256 "8eb1cfb285132e553e226f979625ddf072090d0a508fffb3d0c02f4f320ccbe4"
      def install
        bin.install "oak"
      end
    end
  end

  test do
    system "#{bin}/oak", "--help"
  end
end
