# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oak < Formula
  desc "CLI for Oak, a Git proxy with fine-grained access control"
  homepage "https://oakling.dev"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oakling-dev/homebrew-tap/releases/download/v0.0.1/oak_0.0.1_darwin_amd64.tar.gz"
      sha256 "50549e287838f999f52d3b0931c9c2bc8338a29624cb6ff3e7822f05e6f599ee"

      def install
        bin.install "oak"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oakling-dev/homebrew-tap/releases/download/v0.0.1/oak_0.0.1_darwin_arm64.tar.gz"
      sha256 "b5fbe0c6001044955db20b8998bbe00d2c693f681ceec779f02372f2cdb112cc"

      def install
        bin.install "oak"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oakling-dev/homebrew-tap/releases/download/v0.0.1/oak_0.0.1_linux_amd64.tar.gz"
      sha256 "3c35db58c8f4e64c8b7e760fdf05bdb47e17579a73a1a17851e9bcab80aa681a"
      def install
        bin.install "oak"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oakling-dev/homebrew-tap/releases/download/v0.0.1/oak_0.0.1_linux_arm64.tar.gz"
      sha256 "716f2f01e3eb2ceeeea069bb41df00cbb26b0ea71b2b988f663254d309ef9d84"
      def install
        bin.install "oak"
      end
    end
  end

  test do
    system "#{bin}/oak", "--help"
  end
end
